workflows:
  android-workflow:
    name: Android APK Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        JAVA_VERSION: "17"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Limpiar y compilar APK
        script: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew
          ./gradlew assembleDebug --no-configuration-cache
    artifacts:
      - app/build/outputs/apk/**/*.apk
