workflows:
  android-workflow:
    name: Android APK Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        # Forzamos al servidor a usar Java 17 para evitar el error de Gradle
        JAVA_VERSION: "17"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Dar permisos de ejecución a Gradle
        script: |
          chmod +x gradlew
      - name: Compilar APK de depuración (Debug)
        script: |
          ./gradlew assembleDebug --no-configuration-cache
    artifacts:
      - app/build/outputs/apk/**/*.apk

